name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  # The job running the package tests.
  test:
    name: ${{ matrix.gap-branch }} ${{ matrix.ABI }}
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.11
          - stable-4.10
        ABI: ['']
        include:
            - gap-branch: master
              ABI: 32

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@latest
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}
          GAP_PKGS_TO_BUILD: 'io profiling orb'
      - uses: gap-actions/run-test-for-packages@latest

  # A job to compile the manual with latex and upload it as an artifact.
  manual:
    name: Build manuals
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap-for-packages@latest
      - uses: gap-actions/compile-documentation-for-packages@latest
        with:
          use-latex: true
      - name: "Upload documentation"
        uses: actions/upload-artifact@v1
        with:
          name: manual
          path: ./doc/manual.pdf
